version: '3.2'

services:
  database:
    container_name: database_container
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/logs
      - ./mysql_conf:/etc/mysql/conf.d
      - ./schemas:/docker-entrypoint-initdb.d
    ports:
      - "4408:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  redis:
    container_name: redis_container
    image: redis:7.0.10
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: ["redis-server", "--appendonly", "yes"]

  backend:
    container_name: backend_container
    image: openjdk:21
    restart: always
    volumes:
      - ../backend/qiaoshi-system-0.0.1-SNAPSHOT.jar:/backend.jar
      - ../backend/keystore.p12:/keystore.p12  # 添加证书文件的挂载
    ports:
      - "8080:8080"
    depends_on:
      - database
      - redis
    command: ["java", "-Dspring.profiles.active=prod", "-jar", "/backend.jar"]

  frontend:
    container_name: frontend_container
    image: nginx:1.23.3
    restart: always
    volumes:
      - ../frontend:/app
      - ./nginx_container.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl  # 添加 SSL 证书的挂载
    ports:
      - "80:80"
      - "443:443"  # 添加对 443 端口的映射
    depends_on:
      - backend